### PR TITLE
Fix alignment tests for targets with pointer width < 8 bytes

### LINKED ISSUE #21: `test_new_error` fails on i686
From [this test job](https://github.com/google/zerocopy/actions/runs/3185233602/jobs/5194573658):

```text
error: test failed, to rerun pass '--lib'
thread 'tests::test_new_error' panicked at 'assertion failed: LayoutVerified::<_, u64>::new(&buf.buf[4..]).is_none()', src/lib.rs:2784:9
```

Fix the bug and re-enable the test in `.github/workflows/ci.yml`.

### PR DESCRIPTION
**Pull request by frazar**
The alignment tests relied on the fact that the pointer width is 8 bytes, which is not the case for i686.
Fix the alignment tests so that they work on targets with pointer width of 4 or even 2 bytes.

Fixes #21

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -2768,24 +2768,25 @@ mod tests {
...
-        // should succeed) but an alignment of only 4, which is insufficient.
-        assert!(LayoutVerified::<_, u64>::new(&buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, u64>::new_zeroed(&mut buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, u64>::new_from_prefix(&buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, u64>::new_from_prefix_zeroed(&mut buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, [u64]>::new_slice(&buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, [u64]>::new_slice_zeroed(&mut buf.buf[4..]).is_none());
-        assert!(LayoutVerified::<_, [u64]>::new_slice_from_prefix(&buf.buf[4..], 1).is_none());
-        assert!(LayoutVerified::<_, [u64]>::new_slice_from_prefix_zeroed(&mut buf.buf[4..], 1)
+        // A buffer with an alignment of 8. An odd buffer size is chosen so that the last byte of
```
Comment (joshlf) [inline src/lib.rs:2771]: Can you reflow this and other comments to 80 columns?

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -76,7 +76,7 @@ jobs:
 
     - name: Run tests
       # TODO(#21): Fix `test_new_error` on i686 and re-enable it here.
```
Comment (joshlf) [inline .github/workflows/ci.yml:78]: Can you remove this TODO comment?

**Comment by joshlf** [comment]
Awesome, thanks so much for this, @frazar ! Welcome to zerocopy 😃 

A few small nits, but this looks great!

**Comment by frazar** [comment]
Thank you for your review and your nice words!

Should be ready for merge now.

**Comment by joshlf** [comment]
np! One more small nit and we should be ready to merge.

**Comment by frazar** [comment]
Added the dots to the comments, should be ok now.

**Review by joshlf — APPROVED** [review]
