### PR TITLE
[derive] Implement `#[zerocopy(on_error = skip/fail)]`

### LINKED ISSUE #1769: Support silent failure in derives
Some users want to either auto-generate `#[derive(...)]` attributes (e.g. for use with bindgen) or use a single macro to generate all types uniformly (e.g. libc). Having to manually maintain different derives for different types (e.g. when some types are `IntoBytes` but others aren't) is very laborious.

Instead, we could support a mode in which a failure simply causes zerocopy-derive to not emit a trait impl, but does not cause compilation failure:

```rust
#[derive(FromBytes, IntoBytes)]
#[zerocopy(derive_fail_silently)]
#[repr(transparent)]
struct Foo(bool);
```

In this example, `IntoBytes`, `TryFromBytes`, and `FromZeros` impls would be emitted, but a `FromBytes` impl would not.

For errors emitted by our derive code, this is doable and straightforward. For errors emitted *when trying to compile* code emitted by our derive code, we'll [require the trivial_bounds feature](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5ed3cf3ca70acc63cc8b13fd7a12c45e) to be stabilized.

### PR DESCRIPTION
**Pull request by joshlf**
This attribute allows deriving traits on types that do not meet
requirements (e.g. missing `#[repr(C)]`) by suppressing compilation
errors and emitting no implementation instead. On success, emit
`#[allow(trivial_bounds)]` so that rustc permits code with unsatisfied
trait bounds.

For now, we're keeping this attribute experimental, requiring users to
pass `--cfg zerocopy_derive_on_error` to enable it.

Closes #1769

---

- 👉 #2982

**Latest Update:** v15 — [Compare vs v14](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)

<details>
<summary><strong>📚 Full Patch History</strong></summary>

*Links show the diff between the row version and the column version.*

|Version| v14 | v13 | v12 | v11 | v10 | v9 | v8 | v7 | v6 | v5 | v4 | v3 | v2 | v1 |Base|
|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|:---|
|v15|[v14](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v13](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v12](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v11](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v10](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v15)|
|v14||[v13](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v12](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v11](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v10](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v14)|
|v13|||[v12](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v11](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v10](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v13)|
|v12||||[v11](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v10](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v12)|
|v11|||||[v10](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v11)|
|v10||||||[v9](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10)|
|v9|||||||[v8](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9)|
|v8||||||||[v7](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8)|
|v7|||||||||[v6](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v7)|
|v6||||||||||[v5](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v6)|
|v5|||||||||||[v4](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5)|[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v5)|
|v4||||||||||||[v3](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4)|[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v4)|
|v3|||||||||||||[v2](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3)|[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v3)|
|v2||||||||||||||[v1](/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2)|[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v2)|
|v1|||||||||||||||[Base](/google/zerocopy/compare/main..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v1)|

</details>
<details>
<summary><strong>⬇️ Download this PR</strong></summary>

######

**Branch**
```bash
git fetch origin refs/heads/G4f303a34ae0677fde28c03a0e395212a3bd05ab2 && git checkout -b pr-G4f303a34ae0677fde28c03a0e395212a3bd05ab2 FETCH_HEAD
```

**Checkout**
```bash
git fetch origin refs/heads/G4f303a34ae0677fde28c03a0e395212a3bd05ab2 && git checkout FETCH_HEAD
```

**Cherry Pick**
```bash
git fetch origin refs/heads/G4f303a34ae0677fde28c03a0e395212a3bd05ab2 && git cherry-pick FETCH_HEAD
```

**Pull**
```bash
git pull origin refs/heads/G4f303a34ae0677fde28c03a0e395212a3bd05ab2
```

</details>

*Stacked PRs enabled by [GHerrit](https://github.com/joshlf/gherrit).*

### CODE REVIEW

File: tools/cargo-zerocopy/src/main.rs [hunk 1]
```diff
@@ -167,7 +167,7 @@ fn install_toolchain_or_exit(versions: &Versions, name: &str) -> Result<(), Erro
 fn get_rustflags(name: &str) -> String {
     // See #1792 for context on zerocopy_derive_union_into_bytes.
     let mut flags =
-        "--cfg zerocopy_derive_union_into_bytes --cfg __ZEROCOPY_INTERNAL_USE_ONLY_DEV_MODE"
+        "--cfg zerocopy_derive_on_error --cfg zerocopy_derive_union_into_bytes --cfg __ZEROCOPY_INTERNAL_USE_ONLY_DEV_MODE"
```
Comment (jswrenn) [inline tools/cargo-zerocopy/src/main.rs]: I'd prefer something that conveys the instability, like `zerocopy_unstable_derive_on_error` or even just `zerocopy_unstable` (a la Tokio). There's no reason we couldn't ever adopt cfgs as stable configurators, e.g., for tuple arity limits or optimization tuners.

File: zerocopy-derive/tests/ui-nightly/cfgs/on_error.rs
Comment (jswrenn) [inline zerocopy-derive/tests/ui-nightly/cfgs/on_error.rs:1]: Could you add an `IntoBytes` test here (or wherever appropriate), too? I'm particularly curious to see how this handles our `IntoBytes` heuristic that does the const-eval padding check.

Comment (joshlf) [reply zerocopy-derive/tests/ui-nightly/cfgs/on_error.rs:1]: [Done](https://github.com/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v8..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9#diff-cc2393e5910bfa7050c6e14fcd9955020f53299c76910496fee481b7c9d260cb).

File: tools/cargo-zerocopy/src/main.rs (hunk 1 above)
Comment (joshlf) [reply tools/cargo-zerocopy/src/main.rs]: [Done](https://github.com/google/zerocopy/compare/gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v9..gherrit/G4f303a34ae0677fde28c03a0e395212a3bd05ab2/v10).
