### PR TITLE
[pointer] Support generic `TransmuteFrom` framework

### LINKED ISSUE #1226: Make `AliasingSafe` more powerful
Currently, `AliasingSafe` has the following safety invariants:

```
/// `U: AliasingSafe<T, A, R>` if either of the following conditions holds:
/// - `A` is [`Exclusive`]
/// - `T` and `U` both implement [`Immutable`]
```

However, we could relax this to:

```
/// `U: AliasingSafe<T, A, R>` if either of the following conditions holds:
/// - `A` is [`Exclusive`]
/// - `T` and `U` contain [`UnsafeCell`]s at the same locations
```

In particular, "`T` and `U` implement `Immutable`" is just a special case of " `T` and `U` contain `UnsafeCell`s at the same locations." If we did this, we could add a new `AliasingSafeReason` called `BecauseUnsafeCellsAgree` or something to that effect.

We could then piggy-back on our existing `TransparentWrapper` machinery to provide a blanket impl. In particular, wherever `W: TransparentWrapper<Inner = T, UnsafeCellVariance = Covariant>`, we can infer that `W: AliasingSafe<T, _, BecauseUnsafeCellsAgree>`.

Unfortunately, this construction is less powerful than we'd like. In particular, it is not true in the general case that `W: TransparentWrapper<Inner = T>` implies `T: TransparentWrapper<Inner = W>`, but `AliasingSafe` *is* reflexive in this way. In practice, this causes problems for `transparent_wrapper_into_inner`: If we try to add an `AliasingSafe` bound to `cast_unsized` (a natural thing to do, and it removes a safety precondition), `transparent_wrapper_into_inner`'s `TransparentWrapper` bound isn't sufficient to satisfy `cast_unsized`'s bound. This is prototyped [here](https://github.com/google/zerocopy/compare/aliasing-safe-transparent-wrapper-prototype). Try to build that code and see its compilation errors from `transparent_wrapper_into_inner`.

---

In order to work around this, we should split `TransparentWrapper` into multiple traits. Some of its properties - namely, size equality and `UnsafeCell` agreement - are reflexive, and can go in a separate trait which guarantees this reflexivity (and maybe encodes it in the type system somehow).

### LINKED ISSUE #1359: Generic transmutability
*See also: #1122*

Currently, we have a number of traits that express some aspect of transmutability:
- [`TransparentWrapper`](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/util.rs#L45)
- [`AliasingSafe`](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/pointer/aliasing_safety.rs#L27)

These, in turn, are used to bound certain `Ptr` transmutation methods, e.g.:
- [`transparent_wrapper_into_inner`](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/pointer/ptr.rs#L560)
- [`as_bytes`](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/pointer/ptr.rs#L1006)
- [`try_cast_into`](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/pointer/ptr.rs#L1129)

Both `transparent_wrapper_into_inner` and `as_bytes` implement special cases of a generic `Ptr<T>` to `Ptr<U>` transmutation. This suggests that we could in theory support a more generic `Ptr::transmute` method, supported by a new `TransmutableFrom` trait. This trait would share some similarities with the [built-in transmutability trait](https://github.com/rust-lang/rust/issues/99571). However, as `TransparentWrapper`'s support for invariant variance shows, it might be *more* powerful than that trait in certain ways.

In its most basic form, this API would look something like:

```rust
unsafe trait TransmutableFrom<T> {}

impl<'a, T, A: Aliasing> Ptr<'a, T, (A, Aligned, Valid)> {
    fn transmute<U: TransmutableFrom<T>>(self) -> Ptr<'a, U, (A, Aligned, Valid)>
}
```

However, we will likely want to relax the `Aligned` and `Valid` requirements and post-conditions, and support a generic framework for mapping source invariants (on `T`) to destination invariants (on `U`) - essentially a generalization of what's currently supported with `TransparentWrapper`'s invariant variance concept.

There may be multiple overlapping reasons to support transmuting a particular pair of types. For example, we could imagine the following impls:

```rust
unsafe impl<T: IntoBytes, U: FromBytes> TransmutableFrom<T> for U {}
unsafe impl<T> TransmutableFrom<T> for MaybeUninit<T> {}
```

Currently, these would result in an impl conflict. If [`#[marker]` traits](https://github.com/rust-lang/rust/issues/29864) are stabilized, this won't be an issue - we can just mark `TransmutableFrom` as a `#[marker]` trait. Alternatively, we could use a dummy "reason" parameter to disambiguate, [as we do with `AliasingSafe` today](https://github.com/google/zerocopy/blob/76915d0978e68404d4e53181d462fcc341a71a39/src/pointer/aliasing_safety.rs#L27):

```rust
unsafe trait TransmutableFrom<T, R> {}

enum BecauseIntoBytesFromBytes {}
enum BecauseMaybeUninit {}

unsafe impl<T: IntoBytes, U: FromBytes> TransmutableFrom<T, BecauseIntoBytesFromBytes> for U {}
unsafe impl<T> TransmutableFrom<T> for MaybeUninit<T, BecauseMaybeUninit> {}
```

### LINKED ISSUE #1866: Overhaul `Ptr`'s validity invariant modeling
## Overview

Currently, the invariants enforced by `Ptr` are used strictly as lower bounds. We require code to prove soundness in order to increase the strictness of an invariant, for example to go from any alignment to `Aligned`:

https://github.com/google/zerocopy/blob/1b037c8145526351c96b09ca5bd34892c36844ec/src/pointer/ptr.rs#L779-L781

...but we permit the opposite direction without restriction:

https://github.com/google/zerocopy/blob/1b037c8145526351c96b09ca5bd34892c36844ec/src/pointer/ptr.rs#L936

For alignment, this is sound, but it is not sound for validity as recently illustrated by #2226.

This issue tracks updating `Ptr`'s validity modeling to make it fully sound.

## Proof of Concept

Currently, we model all invariants as lower bounds. Conceptually, an invariant describes what is known about a `Ptr` or its referent at a particular point in the program. Making stronger assertions (e.g., asserting that a `Ptr` with `Any` validity actually refers to a bit-valid value, and thus upgrading its validity to `Valid`) is not sound in the general case. By contrast, making weaker assertions is always sound because it simply entails "forgetting" what is known (e.g., going from `Valid` to `Any`).

This works for alignment, but does not work for aliasing (see #1889) or validity. Consider, for example, adding two seemingly innocuous methods to `Ptr`:
- `forget_valid` modifies the validity invariant on an existing `Ptr` to be `Any`
- `as_maybe_uninit` turns a `Ptr<T>` into a `Ptr<MaybeUninit<T>, (..., ..., Valid)>` (since `MaybeUninit` has no validity requirements)

Taken together, these can be used to produce UB:

https://github.com/google/zerocopy/blob/a3d4387d40e1f0e07f99fcecfa8c17580e066e4a/src/pointer/ptr.rs#L946-L974

Indeed, Miri detects this UB:

```text
test pointer::ptr::test_forget_valid ... error: Undefined Behavior: constructing invalid value: encountered 0x02, but expected a boolean
   --> src/pointer/ptr.rs:974:5
    |
974 |     assert_eq!(b, true);
    |     ^^^^^^^^^^^^^^^^^^^ constructing invalid value: encountered 0x02, but expected a boolean
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE on thread `pointer::ptr::test_forget_valid`:
    = note: inside `pointer::ptr::test_forget_valid` at ~/.rustup/toolchains/nightly-2024-10-09-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/macros/mod.rs:46:22: 46:31
note: inside closure
   --> src/pointer/ptr.rs:945:23
    |
944 | #[test]
    | ------- in this procedural macro expansion
945 | fn test_forget_valid() {
    |                       ^
    = note: this error originates in the macro `assert_eq` which comes from the expansion of the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error; 1 warning emitted

error: test failed, to rerun pass `--lib`
```

## Mental model

As described above, we have historically thought of a `ptr: Ptr<T, Valid>` as encoding the knowledge that `ptr`'s referent is a bit-valid `T`. Naively, I should be able to convert this to `mu: Ptr<MaybeUninit<T>, Valid>` regardless of `t`'s validity invariant; after all, all byte sequences are valid instances of `MaybeUninit<T>`. However, if we rephrase this in terms of references, that's clearly invalid! Going from `&mut T` to `&mut MaybeUninit<T>` is unsound, as the latter reference can be used to write arbitrary bytes to a memory location which is referenced as a `&mut T`.

This highlights that we need to not only consider the *current* type (i.e., the `T` in `Ptr<T>`), but also the types of all references/`Ptr`s from which the current `Ptr` is reborrowed (its "ancestors", to coin a phrase). If we do this, then we can re-conceptualize the invariant as not only providing *knowledge* about the current value of the `Ptr`'s referent, but also a *constraint* about what values are permitted to be written to the referent. In particular, all values written to the referent must be valid for all ancestor references/`Ptr`s.

Note that this only affects validity, but not aliasing or alignment. Aliasing suffers from a similar but different problem, described in #1889. Alignment is a property of a particular `Ptr` (and not of its ancestors) and so it *really is* just a matter of knowledge, not a constraint (in other words, "forgetting" that a `Ptr` is aligned can never cause problems).

Thus, we can re-conceptualize the validity invariant in the following way:
- A `Ptr<T, Validity>` has type `T` and validity `Validity`
- A pair of type and validity, `(T, Validity)`, defines a set of valid values, `V`. For example, `(bool, Valid)` defines the set `{0x00, 0x01}`, and `(bool, AsInitialized)` defines the set `{0x00, ..., 0x255}`. **Note that changing the type *and* changing the validity can both affect `V`.**
- Code is permitted to assume that only values in `V` will be present in the referent
- Code must promise to only write values in `V` to the referent
- Code may only change `V` in a way that doesn't violate the preceding two requirements. As mentioned above, this implicates **both** invariant changes **and** type transmutations.

### LINKED ISSUE #1945: Support arbitrary invariant mappings
*This design is in progress in #1969.*

In https://github.com/google/zerocopy/pull/1896, we added support for "invariant mappings". For a given `I` (where `I = trait Alignment` or `I = trait Validity`), and for all `X: I`, a mapping maps `X` to some `Y: I`.

The idea behind these mappings is that some operations modify the invariants of a `Ptr`. Historically, we had to be conservative and return a new `Ptr` with a single, concrete invariant. For example, `Ptr::cast_unsized` casts to a `Ptr` of a different type, and so it must conservatively assume that the resulting validity is `Unknown`. With mappings, we can encode that, regardless of the types involved, an `Initialized` validity will always map to an `Initialized` validity (because a `Ptr` whose referent bytes are all initialized retains this invariant regardless of what type is has).

However, even invariant mapping is more limited than it could be. In full generality, some operations are valid over multiple possible invariant mappings.

Consider, for example, performing a `Ptr` transmute from `T` to `MaybeUninit<T>`. We can observe that *any* of the following mappings would be valid:
- `Unknown` -> `Unknown`, `AsInitialized`, `Valid`
- `Initialized` -> `Unknown`, `Initialized`, `AsInitialized`, `Valid`
- `AsInitialized` -> `Unknown`, `AsInitialized`, `Valid`
- `Valid` -> `Unknown`, `AsInitialized`, `Valid`

This suggests that we in fact want to encode a *family* of mappings. In this case, there are 3 * 4 * 3 * 3 = 108 valid mappings in this family!

Of course we don't actually want to encode 108 mappings. Not only would that be patently ridiculous, it would also be *too* specific. The real information we need is merely that a given *pair* of invariants constitutes a valid transition. For example, that it's valid to map `Valid` to `AsInitialized`.

Likely the most natural way to encode this is as a trait:

```rust
// Implemented for pairs of `(Type, Validity)`. This won't actually work because it doesn't
// support `Type: ?Sized`, but something similar would.
unsafe trait FromValidity<T: ?Sized, V: Validity> {}

unsafe impl<T> FromValidity<T, Valid> for (MaybeUninit<T>, AsInitialized) {}
// ...
```

This would permit us to support an API like:

```rust
impl<'a, T, I> Ptr<'a, T, I>
where
    T: 'a + ?Sized,
    I: Invariants,
{
    pub fn transmute<U, A, V>(
        self,
    ) -> Ptr<'a, U, (I::Aliasing, A, V)>
    where
        U: ?Sized + FromAlignment<T, I::Alignment> + FromValidity<T, I::Validity>
    { ... }
```

*This API as written might be unsound! We also need to make sure to handle bidirectional validity if the aliasing invariant permits writing to the returned `Ptr`. But the basic idea remains the same, so I haven't bothered to work out the details here.*

This is maximally powerful, but will also cause inference ambiguities in many cases, requiring the user to manually specify the desired invariants. It may be useful to retain the more conservative existing notion of a mapping in order to provide reasonable defaults.

### LINKED ISSUE #2226: `try_transmute_mut`, `TryFromBytes::*mut*` soundness issue
## Progress

- [x] Add `Src: FromBytes` bound to `try_transmute_mut!`
- [x] Release new crate version (0.8.16)
- [x] Add `Self: IntoBytes` bound to `TryFromBytes::*mut*`
   - For why this is required, consider that a `MaybeUninit<u8>` is `TryFromBytes`, but permits writing uninitialized bytes that would invalidated the shadowed `src` reference.
- [x] Release new crate version (0.8.18)
- [ ] Do deeper surgery to make `try_cast_or_pme` sound and `TryFromBytes::*mut*` sound
   - #1866

## Original text

Using zerocopy 0.8.13:

```
use zerocopy::{TryFromBytes, IntoBytes, KnownLayout, Immutable, try_transmute_mut};

#[derive(TryFromBytes, IntoBytes, KnownLayout, Immutable)]
struct T {
    f: bool,
}

fn main() {
    let mut t = T { f: false };
    let slice: &mut [u8; 1] = try_transmute_mut!(&mut t).unwrap();

    slice[0] = u8::MAX;
    println!("f: {}", t.f);
}
```

`cargo +nightly miri run` caught an UB:

```
error: Undefined Behavior: constructing invalid value: encountered 0xff, but expected a boolean
    --> /home/zeling/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:2682:25
     |
2682 |         Display::fmt(if *self { "true" } else { "false" }, f)
     |                         ^^^^^ constructing invalid value: encountered 0xff, but expected a boolean
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
     = note: BACKTRACE:
....
     |
13   |     println!("f: {}", t.f);
     |     ^^^^^^^^^^^^^^^^^^^^^^
     = note: this error originates in the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
```

try_transmute_mut may not be a safe API that can be exposed because it only does validation when creating the reference but the user is free to write whatever bit pattern to the created reference.

### PR DESCRIPTION
**Pull request by joshlf**
This commit removes the `TransparentWrapper` trait and the
`Ptr::transparent_wrapper_into_inner` method. It replaces them with a
new family of transmutation traits which encode more generic
transmutation (from any `T` to any `U`) and a set of `Ptr` methods which
use those traits to bound transmutation operations.

In particular:
- `Dst: TransmuteFrom<Src>` denotes that a by-value transmutation is
  sound
- `Dst: TryTransmuteFromPtr<Src>` denotes that a transmutation is sound
  so long as it can be guaranteed that the source is bit-valid for the
  destination; this is used by e.g. `Ptr::try_into_valid`, which
  performs runtime validation of bit validity
- `Dst: TransmuteFromPtr<Src>` is equivalent to `TransmuteFrom<Src> +
  TryTransmuteFromPtr<Src>`

Some type arguments are omitted in this summary. In particular, all
three traits also take validity invariant parameters for both the source
and destination types. Also, the `[Try]TransmuteFromPtr` traits take an
aliasing parameter.

In order to support these traits, we introduce a generalization of
`Read` known as `MutationCompatible`. `T: MutationCompatible<U, A>`
denotes that *either* `T: Read<A>` and `U: Read<A>` *or* `T` and `U`
have the same interior mutation semantics (formally, it is sound for
`&T` and `&U` to reference the same referent - safe code operating on
these references cannot cause undefined behavior). This is a refinement
of the "`UnsafeCell` agreement" concept that we have used before, but it
supports types which store but don't actually use `UnsafeCell`s. For
example, given a hypothetical `ReadOnly<T>`, the following bound holds:

  usize: MutationCompatible<ReadOnly<AtomicUsize>, Exclusive>

This commit also takes a different approach from the one originally
envisioned in #1945. In particular, it turns out that we don't need a
full type-level mapping concept. Instead, we need a *predicate* over
transitions to determine which ones are valid (e.g., it is valid to go
from a `Valid` `MaybeUninit<T>` to an `Uninit` `MaybeUninit<T>`). By
contrast, the invariant mapping concept suggests that each source
validity has *exactly one* destination validity.

This commit makes progress on #1940 by supporting unsized
transmutations, but we don't yet support size shrinking or expanding
transmutations.

This commit obsoletes #1359, as that issue was predicated upon the
existence of `TransparentWrapper`, which this commit removes.

This commit closes #1226, which suggests supporting `UnsafeCell`
agreement.

Closes #1945
Closes #1359
Closes #2226
Closes #1226
Closes #1866
Makes progress on #1359

Co-authored-by: Jack Wrenn <jswrenn@amazon.com>

---

This PR is on branch [ptr-validity](../tree/ptr-validity).

- #2408

### CODE REVIEW

**Comment by joshlf** [comment]
I think we may have to handle `UnsafeCell` agreement after all. In particular, in order to implement `TryFromBytes` for atomics, we need to be able to go from e.g. `Ptr<AtomicU8>` to `Ptr<UnsafeCell<u8>>` so that we can call `<UnsafeCell<u8> as TryFromBytes>::is_bit_valid`. This will require care since this is unsound for shared aliasing. We know in practice that we'll always be using exclusive aliasing, but I'm not sure how to express that generically.

File: src/wrappers.rs [hunk 1]
```diff
@@ -394,14 +394,14 @@ impl<T: Unaligned> Deref for Unalign<T> {
 
     #[inline(always)]
     fn deref(&self) -> &T {
-        Ptr::from_ref(self).transparent_wrapper_into_inner().bikeshed_recall_aligned().as_ref()
+        Ptr::from_ref(self).transmute().bikeshed_recall_aligned().as_ref()
```
Comment (joshlf) [inline src/wrappers.rs:397]: Bad news: This fails because it requires `T: KnownLayout`, which we wanted to avoid. We might be able to work around it with the `SizedKnownLayout` trick, or we might need to reconsider the `T: KnownLayout` bound.

File: src/pointer/ptr.rs [hunk 2]
```diff
@@ -843,24 +818,24 @@ mod _transitions {
...
             I::Aliasing: Reference,
             I: Invariants<Validity = Initialized>,
         {
             // This call may panic. If that happens, it doesn't cause any soundness
             // issues, as we have not generated any invalid state which we need to
             // fix before returning.
             if T::is_bit_valid(self.reborrow().forget_aligned()) {
-                // SAFETY: If `T::is_bit_valid`, code may assume that `self`
-                // contains a bit-valid instance of `Self`.
+                // TODO: Complete this safety comment.
```
Comment (joshlf) [inline src/pointer/ptr.rs:835]: TODO

File: src/pointer/ptr.rs [hunk 3]
```diff
@@ -902,9 +877,10 @@ mod _casts {
         /// - `u` has the same provenance as `p`
         /// - If `I::Aliasing` is [`Shared`], `UnsafeCell`s in `*u` must exist
         ///   at ranges identical to those at which `UnsafeCell`s exist in `*p`
+        /// TODO: UnsafeCell compatibility
```
Comment (joshlf) [inline src/pointer/ptr.rs:880]: TODO

File: src/pointer/ptr.rs [hunk 4]
```diff
@@ -940,20 +916,29 @@ mod _casts {
...
+            //   - `I::Aliasing` is `Exclusive`
+            //   - `T` and `U` are both `Immutable`
+            // - `T` and `U` contain `UnsafeCell`s at identical locations
+            //
+            // In the first case, `I::Aliasing` is `Exclusive`, and in the
+            // second and third case, `T` and `U` contain `UnsafeCell`s at
+            // identical locations (in the second case, this is because `T` and
+            // `U` contain no `UnsafeCell`s at all).
+            //
+            // TODO: This should also promise UnsafeCell compatibility
```
Comment (joshlf) [inline src/pointer/ptr.rs:941]: TODO

File: zerocopy-derive/src/lib.rs [hunk 5]
```diff
@@ -662,8 +664,14 @@ fn derive_try_from_bytes_struct(
...
                     //   as they do in `*slf`
                     let field_candidate = unsafe {
-                        let project = |slf: *mut Self|
-                            ::zerocopy::util::macro_util::core_reexport::ptr::addr_of_mut!((*slf).#field_names);
+                        let project = |slf: core_reexport::ptr::NonNull<Self>| {
+                            let slf = slf.as_ptr();
+                            let field = core_reexport::ptr::addr_of_mut!((*slf).#field_names);
+                            // TODO: Safety comment. Needs precondition that the
+                            // original `slf` pointer doesn't wrap around
+                            // address space.
```
Comment (joshlf) [inline zerocopy-derive/src/lib.rs:672]: TODO

File: zerocopy-derive/src/lib.rs [hunk 6]
```diff
@@ -720,8 +730,14 @@ fn derive_try_from_bytes_union(
...
                     //   returned pointer's referent contain any `UnsafeCell`s
                     let field_candidate = unsafe {
-                        let project = |slf: *mut Self|
-                            ::zerocopy::util::macro_util::core_reexport::ptr::addr_of_mut!((*slf).#field_names);
+                        let project = |slf: core_reexport::ptr::NonNull<Self>| {
+                            let slf = slf.as_ptr();
+                            let field = core_reexport::ptr::addr_of_mut!((*slf).#field_names);
+                            // TODO: Safety comment. Needs precondition that the
+                            // original `slf` pointer doesn't wrap around
+                            // address space.
```
Comment (joshlf) [inline zerocopy-derive/src/lib.rs:738]: TODO

File: src/pointer/transmute.rs [hunk 7]
```diff
@@ -0,0 +1,312 @@
...
+///
+/// Given `Dst: TryTransmuteFromPtr<Src, A, _>`, callers may assume the
+/// following:
+///
+/// Given `src: Ptr<Src, SI>` where `SI: Invariants<Aliasing = A, Validity =
+/// SV>`, if the referent of `src` contains a `Dst` which conforms to the
+/// validity `DV`, then it is sound to transmute `src` into `dst: Ptr<Dst, DI>`
+/// whre `DI: Invariants<Aliasing = A, Validity = DV>`.
+///
+/// TODO: Mention alignment
```
Comment (joshlf) [inline src/pointer/transmute.rs:29]: TODO

File: src/pointer/transmute.rs [hunk 8]
```diff
@@ -0,0 +1,312 @@
...
+/// - Forwards transmutation: Any of the following hold:
+///     - So long as `dst` is active, no mutation of `dst`'s referent is allowed
+///       except via `dst` itself
+///     - The set of `DV`-valid `Dst`s is a superset of the set of `SV`-valid
+///       `Src`s
+/// - Reverse transmutation: Any of the following hold:
+///     - `dst` does not permit mutation of its referent
+///     - The set of `DV`-valid `Dst`s is a subset of the set of `SV`-valid
+///       `Src`s
+/// - Interior mutation: TODO (ie, at least one of `Exclusive` or `Immutable`
```
Comment (joshlf) [inline src/pointer/transmute.rs:46]: TODO

File: src/pointer/transmute.rs [hunk 9]
```diff
@@ -0,0 +1,312 @@
...
+///   required)
+///
+/// ## Proof
+///
+/// TODO: Prove that the pre-conditions imply the post-conditions.
```
Comment (joshlf) [inline src/pointer/transmute.rs:51]: TODO

File: src/pointer/transmute.rs [hunk 10]
```diff
@@ -0,0 +1,312 @@
...
+}
+
+unsafe impl<Src: ?Sized, Dst: ?Sized, A: Aliasing, SV: Validity, DV: Validity, R>
+    TransmuteFromPtr<Src, A, SV, DV, R> for Dst
+where
+    Dst: TransmuteFrom<Src, SV, DV> + TryTransmuteFromPtr<Src, A, SV, DV, R>,
+{
+}
+
+/// TODO
```
Comment (joshlf) [inline src/pointer/transmute.rs:131]: TODO

File: src/pointer/transmute.rs [hunk 11]
```diff
@@ -0,0 +1,312 @@
...
+where
+    Src: ?Sized,
+    Dst: FromBytes + ?Sized,
+    Src: SizeEq<Dst>,
+{
+}
+
+// TODO: This seems like a smell - the soundness of this bound has nothing to do
+// with `Src` or `Dst` - we're basically just saying `[u8; N]` is transmutable
+// into `[u8; N]`.
```
Comment (joshlf) [inline src/pointer/transmute.rs:186]: TODO

File: src/pointer/transmute.rs [hunk 12]
```diff
@@ -0,0 +1,312 @@
...
+where
+    Src: ?Sized,
+    Dst: ?Sized,
+    Src: SizeEq<Dst>,
+{
+}
+
+// TODO: This seems like a smell - the soundness of this bound has nothing to do
+// with `Src` or `Dst` - we're basically just saying `MaybeUninit<[u8; N]>` is
+// transmutable into `MaybeUninit<[u8; N]>`.
```
Comment (joshlf) [inline src/pointer/transmute.rs:202]: TODO

File: src/impls.rs [hunk 13]
```diff
@@ -468,10 +470,8 @@ mod atomics {
             unsafe_impl!(AtomicI8: Unaligned);
             assert_unaligned!(AtomicBool, AtomicU8, AtomicI8);
 
-            /// SAFETY:
-            /// All of these pass an atomic type and that type's native equivalent, as
-            /// required by the macro safety preconditions.
-            unsafe_impl_transparent_wrapper_for_atomic!(AtomicU8 [u8], AtomicI8 [i8], AtomicBool [bool]);
+            /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:473]: TODO

File: src/impls.rs [hunk 14]
```diff
@@ -482,13 +482,11 @@ mod atomics {
...
 
-        impl_traits_for_atomics!(AtomicU16, AtomicI16);
+        impl_traits_for_atomics!(AtomicU16[u16], AtomicI16[i16]);
 
         safety_comment! {
-            /// SAFETY:
-            /// All of these pass an atomic type and that type's native equivalent, as
-            /// required by the macro safety preconditions.
-            unsafe_impl_transparent_wrapper_for_atomic!(AtomicU16 [u16], AtomicI16 [i16]);
+            /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:488]: TODO

File: src/impls.rs [hunk 15]
```diff
@@ -499,13 +497,11 @@ mod atomics {
...
 
-        impl_traits_for_atomics!(AtomicU32, AtomicI32);
+        impl_traits_for_atomics!(AtomicU32[u32], AtomicI32[i32]);
 
         safety_comment! {
-            /// SAFETY:
-            /// All of these pass an atomic type and that type's native equivalent, as
-            /// required by the macro safety preconditions.
-            unsafe_impl_transparent_wrapper_for_atomic!(AtomicU32 [u32], AtomicI32 [i32]);
+            /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:503]: TODO

File: src/impls.rs [hunk 16]
```diff
@@ -516,13 +512,11 @@ mod atomics {
...
 
-        impl_traits_for_atomics!(AtomicU64, AtomicI64);
+        impl_traits_for_atomics!(AtomicU64[u64], AtomicI64[i64]);
 
         safety_comment! {
-            /// SAFETY:
-            /// All of these pass an atomic type and that type's native equivalent, as
-            /// required by the macro safety preconditions.
-            unsafe_impl_transparent_wrapper_for_atomic!(AtomicU64 [u64], AtomicI64 [i64]);
+            /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:518]: TODO

File: src/impls.rs [hunk 17]
```diff
@@ -533,21 +527,27 @@ mod atomics {
...
-        impl_for_transparent_wrapper!(T => FromZeros for AtomicPtr<T>);
+        impl_for_transmute_from!(T => TryFromBytes for AtomicPtr<T> [UnsafeCell<*mut T>]);
 
         safety_comment! {
-            /// SAFETY:
-            /// This passes an atomic type and that type's native equivalent, as
-            /// required by the macro safety preconditions.
-            unsafe_impl_transparent_wrapper_for_atomic!(AtomicUsize [usize], AtomicIsize [isize]);
-            unsafe_impl_transparent_wrapper_for_atomic!(T => AtomicPtr<T> [*mut T]);
+            /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:548]: TODO

File: src/impls.rs [hunk 18]
```diff
@@ -577,39 +650,76 @@ safety_comment! {
...
-impl_for_transparent_wrapper!(T: IntoBytes => IntoBytes for Wrapping<T>);
-impl_for_transparent_wrapper!(T: Unaligned => Unaligned for Wrapping<T>);
+impl_for_transmute_from!(T: TryFromBytes => TryFromBytes for Wrapping<T>[T]);
+impl_for_transparent_wrapper!(T: FromZeros => FromZeros for Wrapping<T>[T]);
+impl_for_transparent_wrapper!(T: FromBytes => FromBytes for Wrapping<T>[T]);
+impl_for_transparent_wrapper!(T: IntoBytes => IntoBytes for Wrapping<T>[T]);
 assert_unaligned!(Wrapping<()>, Wrapping<u8>);
 
+safety_comment! {
+    /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:660]: TODO

File: src/impls.rs [hunk 19]
```diff
@@ -577,39 +650,76 @@ safety_comment! {
...
+}
+
 safety_comment! {
     /// SAFETY:
     /// `TryFromBytes` (with no validator), `FromZeros`, `FromBytes`:
     /// `MaybeUninit<T>` has no restrictions on its contents.
     unsafe_impl!(T => TryFromBytes for CoreMaybeUninit<T>);
     unsafe_impl!(T => FromZeros for CoreMaybeUninit<T>);
     unsafe_impl!(T => FromBytes for CoreMaybeUninit<T>);
+    /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:672]: TODO

File: src/impls.rs [hunk 20]
```diff
@@ -577,39 +650,76 @@ safety_comment! {
...
 assert_unaligned!(CoreMaybeUninit<()>, CoreMaybeUninit<u8>);
 
-impl_for_transparent_wrapper!(T: ?Sized + Immutable => Immutable for ManuallyDrop<T>);
-impl_for_transparent_wrapper!(T: ?Sized + TryFromBytes => TryFromBytes for ManuallyDrop<T>);
-impl_for_transparent_wrapper!(T: ?Sized + FromZeros => FromZeros for ManuallyDrop<T>);
-impl_for_transparent_wrapper!(T: ?Sized + FromBytes => FromBytes for ManuallyDrop<T>);
-impl_for_transparent_wrapper!(T: ?Sized + IntoBytes => IntoBytes for ManuallyDrop<T>);
-impl_for_transparent_wrapper!(T: ?Sized + Unaligned => Unaligned for ManuallyDrop<T>);
+safety_comment! {
+    /// SAFETY: TODO
```
Comment (joshlf) [inline src/impls.rs:679]: TODO

**Review by jswrenn — APPROVED** [review]
Developed and reviewed in tandem!
