### PR TITLE
Account for alignment directives in `derive(IntoBytes)`

### LINKED ISSUE #3063: `derive(IntoBytes)` accepts DSTs with trailing padding
`derive(IntoBytes)` erroneously accepts `repr(C, align(X))` DSTs with dynamic trailing padding; e.g.

```rust
#[derive(IntoBytes)]
#[repr(C, align(4))]
struct Unsound([u8]);
```

The derive accepts this because it merely confirms that `[u8]` is `Unaligned`, whereas it *should* be failing on the `align` directive. The sized analysis codepath correctly takes this into account; e.g.:

```rust
#[derive(IntoBytes)] // Compile error!
#[repr(C, align(4))]
struct Sized([u8; 3]);
```

Bug confirmed on `v0.8.39` (latest release at time of reporting), but likely present on earlier releases. Looks like this slipped in with #2679, and was probably missed because the testing infra borrowed for the sized case also doesn't reason about outer `align` directives.

### LINKED ISSUE #3067: `derive(IntoBytes)` accepts enums with padding
`derive(IntoBytes)` erroneously accepts `repr(C/int, align(X))` enums with static padding; e.g.

```rust
#[derive(zerocopy::IntoBytes)]
#[repr(u8, align(2))]
enum HasAlign {
    A
}
```

Fix in progress in #3064.

### PR DESCRIPTION
**Pull request by jswrenn**
This fixes #3063 by threading alignment directives into the padding
check macros, and fixes #3067 by unconditionally emitting the padding
check even in the absence of fields (thus ensuring that there exists a
padding check into which alignment directives can be threaded).

Fixes #3063, #3067

---

- 👉 #3064

**Latest Update:** v8 — [Compare vs v7](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)

<details>
<summary><strong>📚 Full Patch History</strong></summary>

*Links show the diff between the row version and the column version.*

|Version| v7 | v6 | v5 | v4 | v3 | v2 | v1 |Base|
|:---|:---|:---|:---|:---|:---|:---|:---|:---|
|v8|[vs v7](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v6](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v5](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v4](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v3](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v8)|
|v7||[vs v6](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs v5](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs v4](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs v3](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v7)|
|v6|||[vs v5](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|[vs v4](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|[vs v3](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v6)|
|v5||||[vs v4](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5)|[vs v3](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5)|[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v5)|
|v4|||||[vs v3](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4)|[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v4)|
|v3||||||[vs v2](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3)|[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v3)|
|v2|||||||[vs v1](/google/zerocopy/compare/gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2)|[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v2)|
|v1||||||||[vs Base](/google/zerocopy/compare/main..gherrit/Gf18655827d1c30e4421c83579b962bf7aa453969/v1)|

</details>
<details>
<summary><strong>⬇️ Download this PR</strong></summary>

######

**Branch**
```bash
git fetch origin refs/heads/Gf18655827d1c30e4421c83579b962bf7aa453969 && git checkout -b pr-Gf18655827d1c30e4421c83579b962bf7aa453969 FETCH_HEAD
```

**Checkout**
```bash
git fetch origin refs/heads/Gf18655827d1c30e4421c83579b962bf7aa453969 && git checkout FETCH_HEAD
```

**Cherry Pick**
```bash
git fetch origin refs/heads/Gf18655827d1c30e4421c83579b962bf7aa453969 && git cherry-pick FETCH_HEAD
```

**Pull**
```bash
git pull origin refs/heads/Gf18655827d1c30e4421c83579b962bf7aa453969
```

</details>

*Stacked PRs enabled by [GHerrit](https://github.com/joshlf/gherrit).*

### CODE REVIEW

File: zerocopy-derive/src/util.rs [hunk 1]
```diff
@@ -566,6 +568,22 @@ impl<'a> ImplBlockBuilder<'a> {
             .padding_check
             .and_then(|check| (!fields.is_empty()).then_some(check))
             .map(|check| {
+                let repr =
+                    Repr::<PrimitiveRepr, NonZeroU32>::from_attrs(&self.ctx.ast.attrs).unwrap();
```
[the remark this answers is not in the document]
Comment (jswrenn) [reply zerocopy-derive/src/util.rs:573]: Disagree. The code bloat cost of threading a generic `Repr` into `ImplBlockBuilder` is not worth it, and the correctness risk of individually threading the alignment modifiers into `ImplBlockBuilder` (and trusting we never get them backwards) is not worth it. And, as noted in a comment, the repr being parsed here, `Repr::<PrimitiveRepr, NonZeroU32>`, is a superset of the repr permitted by structs, unions, and enums.

File: src/util/macro_util.rs [hunk 2]
```diff
@@ -329,9 +329,12 @@ pub use __size_of::size_of;
 #[doc(hidden)] // `#[macro_export]` bypasses this module's `#[doc(hidden)]`.
 #[macro_export]
 macro_rules! struct_padding {
-    ($t:ty, [$($ts:ty),*]) => {
+    ($t:ty, $align:expr, $packed:expr, [$($ts:ty),*]) => {{
```
Comment (joshlf) [inline src/util/macro_util.rs]:
```suggestion
    ($t:ty, $_align:expr, $_packed:expr, [$($ts:ty),*]) => {{
```

File: src/util/macro_util.rs [hunk 3]
```diff
@@ -379,7 +382,10 @@ macro_rules! repr_c_struct_has_padding {
 #[doc(hidden)] // `#[macro_export]` bypasses this module's `#[doc(hidden)]`.
 #[macro_export]
 macro_rules! union_padding {
-    ($t:ty, [$($ts:ty),*]) => {{
+    ($t:ty, $align:expr, $packed:expr, [$($ts:ty),*]) => {{
```
Comment (joshlf) [inline src/util/macro_util.rs]:
```suggestion
    ($t:ty, $_align:expr, $_packed:expr, [$($ts:ty),*]) => {{
```

File: src/util/macro_util.rs [hunk 4]
```diff
@@ -410,7 +416,14 @@ macro_rules! union_padding {
 #[doc(hidden)] // `#[macro_export]` bypasses this module's `#[doc(hidden)]`.
 #[macro_export]
 macro_rules! enum_padding {
-    ($t:ty, $disc:ty, $([$($ts:ty),*]),*) => {{
+    ($t:ty, $align:expr, $packed:expr, $disc:ty, $([$($ts:ty),*]),*) => {{
```
Comment (joshlf) [inline src/util/macro_util.rs]:
```suggestion
    ($t:ty, $_align:expr, $packed:expr, $disc:ty, $([$($ts:ty),*]),*) => {{
```

File: src/util/macro_util.rs (hunk 2 above)
Comment (jswrenn) [reply src/util/macro_util.rs]: [Resolved](https://github.com/google/zerocopy/compare/ea77523debac4de11debb92ea08debc9594ff8a4..7b5977f9a9f74d3e930e3247065322e9a74eade2#diff-2abf6454394ca2a0779f4bf7cc0631f23cf1dc484566b5937e8a1ad9a5b9e3e8R332)

File: src/util/macro_util.rs (hunk 4 above)
Comment (jswrenn) [reply src/util/macro_util.rs]: [Resolved](https://github.com/google/zerocopy/compare/ea77523debac4de11debb92ea08debc9594ff8a4..7b5977f9a9f74d3e930e3247065322e9a74eade2#diff-2abf6454394ca2a0779f4bf7cc0631f23cf1dc484566b5937e8a1ad9a5b9e3e8R419)

File: src/util/macro_util.rs (hunk 3 above)
Comment (jswrenn) [reply src/util/macro_util.rs]: [Resolved](https://github.com/google/zerocopy/compare/ea77523debac4de11debb92ea08debc9594ff8a4..7b5977f9a9f74d3e930e3247065322e9a74eade2#diff-2abf6454394ca2a0779f4bf7cc0631f23cf1dc484566b5937e8a1ad9a5b9e3e8R385)
