### PR TITLE
Fix as_bytes() test for big endian targets

### LINKED ISSUE #23: `test_as_bytes_methods` fails on powerpc
From [this test job](https://github.com/google/zerocopy/actions/runs/3185927469/jobs/5196030735):

```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0]`,
 right: `[1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]`', src/lib.rs:2885:9
```

Fix the bug and re-enable the test in `.github/workflows/ci.yml`.

### PR DESCRIPTION
**Pull request by frazar**
The tests for the as_bytes() method assumed that bytes are stored in little endian order, which is not the case for PowerPC. Fix the alignment tests so that they work on both little and big endian targets.

Fixes #23

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -2872,33 +2872,50 @@ mod tests {
         }
 
         let mut foo = Foo { a: 1, b: Wrapping(2), c: None };
+
         // Test that we can access the underlying bytes, and that we get the
         // right bytes and the right number of bytes.
-        assert_eq!(foo.as_bytes(), [1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]);
+
+        #[cfg(target_endian = "little")]
```
Comment (joshlf) [inline src/lib.rs:2879]: Can you use `cfg!` instead to make this a bit cleaner?

```rust
let expected: Vec<u8> = if cfg!(target_endian = "little") {
    vec![1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
} else {
    vec![0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0]
};
```

Same below.

File: src/lib.rs [hunk 2]
```diff
@@ -2872,33 +2872,50 @@ mod tests {
...
+        #[cfg(target_endian = "big")]
+        let expected: Vec<u8> = vec![0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0];
+        assert_eq!(foo.as_bytes(), expected.as_bytes());
+
         // Test that changes to the underlying byte slices are reflected in the
         // original object.
         foo.as_bytes_mut()[0] = 3;
-        assert_eq!(foo, Foo { a: 3, b: Wrapping(2), c: None });
+        #[cfg(target_endian = "little")]
+        let expected = Foo { a: 0x00_00_00_03, b: Wrapping(2), c: None };
```
Comment (joshlf) [inline src/lib.rs:2889]: Can you pull `a` out separately? Something like:

```rust
let a = if cfg!(target_endian = "little") { 0x00_00_00_03 } else { 0x03_00_00_01 };
let expected = Foo { a, b: Wrapping(2), c: None };
```

Same below.

**Comment by joshlf** [comment]
Awesome, thanks @frazar! Left a few comments.

**Comment by frazar** [comment]
Great! Should be ready now.

**Review by joshlf — APPROVED** [review]

**Comment by joshlf** [comment]
Thanks again!

**Comment by joshlf** [comment]
> May I ask you to add the "Hacktoberfest-accepted" label to this PR? Thanks!

Done!

**Comment by frazar** [comment]
Great, thanks!
