### PR TITLE
[derive] Avoid ambiguities referring to associated items

### LINKED ISSUE #2915: Enums with a variant named `Type`, at least one variant with data and `#[derive(TryFromBytes)]` generate an error on stable rust.
Creating an enum with a `Type` variant, as well as at least one variant that holds data produces the following error:

```rust
#[derive(TryFromBytes)]
#[repr(u8)]
enum MyEnum {
    Type,
    OtherWithData(u8),
}
```

```
error: ambiguous associated item
    --> golm/src/compile/types.rs:7:24
     |
   7 | #[derive(Debug, Clone, TryFromBytes)]
     |                        ^^^^^^^^^^^^
     |
     = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
     = note: for more information, see issue #57644 <https://github.com/rust-lang/rust/issues/57644>
note: `Type` could refer to the variant defined here
    --> golm/src/compile/types.rs:12:5
     |
  12 |     Type = 1,
     |     ^^^^
note: `Type` could also refer to the associated type defined here
    --> /home/owl/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zerocopy-0.8.33/src/lib.rs:1139:5
     |
1139 |     type Type: ?Sized;
     |     ^^^^^^^^^^^^^^^^^
     = note: `#[deny(ambiguous_associated_items)]` (part of `#[deny(future_incompatible)]`) on by default
     = note: this error originates in the derive macro `TryFromBytes` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by joshlf**
Release 0.8.34.

Closes #2915

---

- &#x3000; #2918
- 👉 #2917

**Latest Update:** v4 — [Compare vs v3](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v3..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v4)

<details>
<summary><strong>📚 Full Patch History</strong></summary>

*Links show the diff between the row version and the column version.*

|Version| v3 | v2 | v1 |Base|
|:---|:---|:---|:---|:---|
|v4|[vs v3](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v3..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v4)|[vs v2](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v2..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v4)|[vs v1](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v1..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v4)|[vs Base](/google/zerocopy/compare/main..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v4)|
|v3||[vs v2](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v2..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v3)|[vs v1](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v1..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v3)|[vs Base](/google/zerocopy/compare/main..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v3)|
|v2|||[vs v1](/google/zerocopy/compare/gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v1..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v2)|[vs Base](/google/zerocopy/compare/main..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v2)|
|v1||||[vs Base](/google/zerocopy/compare/main..gherrit/Gc3a755f2c72ce9e1d064eccd1101a5c37acb211e/v1)|

</details>

### CODE REVIEW

File: zerocopy-derive/src/util.rs [hunk 1]
```diff
@@ -601,6 +601,7 @@ pub(crate) fn const_block(items: impl IntoIterator<Item = Option<TokenStream>>)
             non_ascii_idents,
             clippy::missing_inline_in_public_items,
         )]
+        #[deny(ambiguous_associated_items)]
```
Comment (joshlf) [inline zerocopy-derive/src/util.rs:604]: Is this perhaps a bad idea in case user code contains const blocks (e.g. in type definitions) which internally use ambiguous associated items? This could turn what would otherwise be a warning into an error. Then again, they could always just put `#[allow(ambiguous_associated_items)]` on their code (since we `deny` rather than `forbid` the lint).

I'm leaning towards thinking this is fine, but I figured I'd call it out in case you disagree, @jswrenn.
