### PR TITLE
Practice good `Self` hygiene

### LINKED ISSUE #2116: Cycle detected when evaluating trait selection obligation
With `zerocopy` 0.8.11, the following code failed to compile:

```rust
use zerocopy::*;

#[derive(KnownLayout)]
#[repr(C)]
pub struct Dummy([u8; Self::CONST]);

impl Dummy {
    const CONST: usize = 42;
}
```

```plain
error[E0391]: cycle detected when evaluating trait selection obligation `_::__ZerocopyKnownLayoutMaybeUninit: core::iter::traits::collect::IntoIterator`
  |
note: ...which requires evaluating type-level constant...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires const-evaluating + checking `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires caching mir of `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}` for CTFE...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires elaborating drops for `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires borrow-checking `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires const checking `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires building MIR for `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires match-checking `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:23
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                       ^^^^^^^^^^^
note: ...which requires type-checking `_::__ZerocopyKnownLayoutMaybeUninit::0::{constant#0}`...
 --> src/lib.rs:5:29
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                             ^^^^^
  = note: ...which again requires evaluating trait selection obligation `_::__ZerocopyKnownLayoutMaybeUninit: core::iter::traits::collect::IntoIterator`, completing the cycle
note: cycle used when type-checking `_::<impl at src/lib.rs:3:10: 3:21>::{constant#0}`
 --> src/lib.rs:5:29
  |
5 | pub struct Dummy([u8; Self::CONST]);
  |                             ^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

For more information about this error, try `rustc --explain E0391`.
```

This compiles on 0.8.10.

```
> rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
> cargo --version
cargo 1.83.0 (5ffbef321 2024-10-29)
> cat Cargo.toml
[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
#zerocopy = { version = "=0.8.11", features = ["derive"] }
zerocopy = { version = "=0.8.10", features = ["derive"] }
```

### PR DESCRIPTION
**Pull request by jswrenn**
This commit revises the `KnownLayout` derive on `repr(C)` target structs to preserve the correct resolution of `Self` when constructing `__ZerocopyKnownLayoutMaybeUninit`. This type contains a `MaybeUninit` version of each of the target struct's field types. Previously, it achieved this by simply copying the tokens corresponding to field types from the definition of the target struct into the definition of `__ZerocopyKnownLayoutMaybeUninit`

However, on types like this:

```rust
#[repr(C)]
struct Struct([u8; Self::N]);
```

…this approach is insufficient. Pasted into `__ZerocopyKnownLayoutMaybeUninit`, `Self` ceases to refer to the target struct and instead refers to `__ZerocopyKnownLayoutMaybeUninit`.

To preserve `Self` hygiene, this commit defines a struct for projecting the field types of the target struct based on their index:

```rust
pub unsafe trait Field<const N: usize> {
    type Type: ?Sized;
}
```

…then implements it for each of the field types of the target struct; e.g.:

```rust
impl Field<0> for Struct {
    type Type = [u8; Self::N];
}
```

With this, the fields of `__ZerocopyKnownLayoutMaybeUninit` can be defined hygienically; e.g., as `<Struct as Field<0>>::Type`.

Fixes #2116

### CODE REVIEW

**Comment by joshlf** [comment]
> Unfortunately, with the added `Field` indirection in `trailing_field_ty`, the hack here to avoid an ICE on our MSRV no longer does so: https://github.com/google/zerocopy/blob/e3c52768b0143100e09eec3aa55f8e77295bafe4/zerocopy-derive/src/lib.rs#L320-L327
> 
> 
> 
> This is the test case that exhibits the ICE: https://github.com/google/zerocopy/blob/ac7b8e8e98810fdc754fe79734a2235be3bbe3db/zerocopy-derive/tests/struct_known_layout.rs#L50-L59
> 
> 
> 
> The problematic quality here is the lifetimes in the trailing field. Lifetimes in leading fields are unproblematic.
> 
> 
> 
> Not yet sure how to work around this.

Hot take: what if we don't work around it? The likelihood of someone encountering this in practice is extremely low since our MSRV is so old. If someone does, we can explain that it's a compiler bug and thus not really our fault.

I'd want to figure out what toolchain fixed this ICE. If it's a recent toolchain, then I wouldn't want to go this route, but if it's like 1.58 or something, then I'm okay with it.

**Comment by joshlf** [comment]
> Unfortunately, with the added `Field` indirection in `trailing_field_ty`, the hack here to avoid an ICE on our MSRV no longer does so: https://github.com/google/zerocopy/blob/e3c52768b0143100e09eec3aa55f8e77295bafe4/zerocopy-derive/src/lib.rs#L320-L327
> 
> 
> 
> This is the test case that exhibits the ICE: https://github.com/google/zerocopy/blob/ac7b8e8e98810fdc754fe79734a2235be3bbe3db/zerocopy-derive/tests/struct_known_layout.rs#L50-L59
> 
> 
> 
> The problematic quality here is the lifetimes in the trailing field. Lifetimes in leading fields are unproblematic.
> 
> 
> 
> Not yet sure how to work around this.

Hot take: what if we don't work around it? The likelihood of someone encountering this in practice is extremely low since our MSRV is so old. If someone does, we can explain that it's a compiler bug and thus not really our fault.

I'd want to figure out what toolchain fixed this ICE. If it's a recent toolchain, then I wouldn't want to go this route, but if it's like 1.58 or something, then I'm okay with it.

**Comment by jswrenn** [comment]
The last problematic rustc version is 1.61, released May 19, 2022.

**Comment by jswrenn** [comment]
> The problematic quality here is the lifetimes in the trailing field. Lifetimes in leading fields are unproblematic.

Static lifetimes are also unproblematic.

File: src/util/macro_util.rs [hunk 1]
```diff
@@ -32,6 +32,17 @@ use crate::{
     Immutable, IntoBytes, Ptr, TryFromBytes, Unalign, ValidityError,
 };
 
+/// Projects the type of the field at `Index` in `Self`.
+///
+/// # Safety
+///
+/// Unsafe code may assume that this accurately reflects the definition of
+/// `Self`.
```
Comment (joshlf) [inline src/util/macro_util.rs:40]: Document what the `Index` type represents? IMO, "index" is an odd name since this will really end up being a type like `__Zerocopy_Field_a`. I assume this is a holdover from when it was a numerical const index?

File: zerocopy-derive/src/lib.rs [hunk 2]
```diff
@@ -266,11 +266,48 @@ fn derive_known_layout_inner(ast: &DeriveInput, _top_level: Trait) -> Result<Tok
                 Default::default()
             };
 
+            let field_index =
+                |name| Ident::new(&format!("__Zerocopy_Field_{}", name), ident.span());
```
Comment (joshlf) [inline zerocopy-derive/src/lib.rs:270]: Same comment here and below about the nomenclature "index". If you rename it in the `Field` trait, make sure to similarly rename it here.

File: zerocopy-derive/src/lib.rs [hunk 3]
```diff
@@ -279,7 +316,11 @@ fn derive_known_layout_inner(ast: &DeriveInput, _top_level: Trait) -> Result<Tok
                 #repr
                 #[doc(hidden)]
                 #vis struct __ZerocopyKnownLayoutMaybeUninit<#params> (
-                    #(::zerocopy::util::macro_util::core_reexport::mem::MaybeUninit<#leading_fields_tys>,)*
+                    #(::zerocopy::util::macro_util::core_reexport::mem::MaybeUninit<
+                        <#ident #ty_generics as
+                            ::zerocopy::util::macro_util::Field<#leading_field_indices>
+                        >::Type
+                    >,)*
```
Comment (joshlf) [inline zerocopy-derive/src/lib.rs:323]: Comment here explaining why we indirect via `Field` rather than just using the field types directly?

File: zerocopy-derive/tests/struct_known_layout.rs [hunk 4]
```diff
@@ -46,16 +48,37 @@ util_assert_impl_all!(TypeParams<'static, (), imp::IntoIter<()>>: imp::KnownLayo
...
+        [T; N],
+        imp::PhantomData<&'a &'b ()>,
+    )
+    where
+        'a: 'b,
+        'b: 'a,
+        T: 'a + 'b + imp::KnownLayout;
+
+    util_assert_impl_all!(WithParams<'static, 'static, u8, 42>: imp::KnownLayout);
+};
```
Comment (joshlf) [inline zerocopy-derive/tests/struct_known_layout.rs:69]: Also add a test which is similar but uses static lifetimes and is compiled on all toolchains?

File: zerocopy-derive/tests/struct_known_layout.rs [hunk 5]
```diff
@@ -46,16 +48,37 @@ util_assert_impl_all!(TypeParams<'static, (), imp::IntoIter<()>>: imp::KnownLayo
...
+
+// Deriving `KnownLayout` should work if the struct references `Self`
```
Comment (joshlf) [inline zerocopy-derive/tests/struct_known_layout.rs:71]: Mention the relevant issue number?

File: src/util/macro_util.rs (hunk 1 above)
Comment (jswrenn) [reply src/util/macro_util.rs:40]: It's an index in the most general sense — a label used for lookups. When we use `Field` to project into enums (whose fields cannot have visibility modifiers), we'll use a single `#vis struct Index<const N: usize>` type.

File: zerocopy-derive/tests/struct_known_layout.rs (hunk 5 above)
Comment (jswrenn) [reply zerocopy-derive/tests/struct_known_layout.rs]: [Done](https://github.com/google/zerocopy/compare/c7cfc8df03d86f6f93d73c8bc37729ad12eebd96..2cfcc5a8c3baf2a66dbb18fe633ba234a411a155#diff-85b159abf94564dfae9563267afd74a8b55832be2174e5cfef9522c1a8b6955cR89-R90)

File: zerocopy-derive/tests/struct_known_layout.rs (hunk 4 above)
Comment (jswrenn) [reply zerocopy-derive/tests/struct_known_layout.rs:69]: [Done](https://github.com/google/zerocopy/compare/c7cfc8df03d86f6f93d73c8bc37729ad12eebd96..2cfcc5a8c3baf2a66dbb18fe633ba234a411a155#diff-85b159abf94564dfae9563267afd74a8b55832be2174e5cfef9522c1a8b6955cR71-R87)

File: zerocopy-derive/src/lib.rs (hunk 3 above)
Comment (jswrenn) [reply zerocopy-derive/src/lib.rs:328]: [Done](https://github.com/google/zerocopy/compare/c7cfc8df03d86f6f93d73c8bc37729ad12eebd96..2cfcc5a8c3baf2a66dbb18fe633ba234a411a155#diff-977c29e6cf079bd7307f811df24f99633df603962785c583145eb6250b0e12daR318-R320)

File: zerocopy-derive/src/lib.rs (hunk 2 above)
Comment (jswrenn) [reply zerocopy-derive/src/lib.rs:272]: [Done](https://github.com/google/zerocopy/compare/c7cfc8df03d86f6f93d73c8bc37729ad12eebd96..2cfcc5a8c3baf2a66dbb18fe633ba234a411a155#diff-977c29e6cf079bd7307f811df24f99633df603962785c583145eb6250b0e12daR269-R270)

File: src/util/macro_util.rs (hunk 1 above)
Comment (jswrenn) [reply src/util/macro_util.rs]: [Done](https://github.com/google/zerocopy/compare/c7cfc8df03d86f6f93d73c8bc37729ad12eebd96..2cfcc5a8c3baf2a66dbb18fe633ba234a411a155#diff-2abf6454394ca2a0779f4bf7cc0631f23cf1dc484566b5937e8a1ad9a5b9e3e8R37-R39)

File: zerocopy-derive/src/lib.rs (hunk 3 above)
Comment (joshlf) [reply zerocopy-derive/src/lib.rs:328]: Also mention #2116 in this comment?

**Review by joshlf — APPROVED** [review]
One more change requested, but otherwise LGTM.

File: zerocopy-derive/src/lib.rs (hunk 3 above)
Comment (jswrenn) [reply zerocopy-derive/src/lib.rs:328]: [Done](https://github.com/google/zerocopy/compare/2cfcc5a8c3baf2a66dbb18fe633ba234a411a155..9f787224d7aa909c7c030422ded4f8495cacc35e)
